import styled from "styled-components";

export const Loading = styled.div`
    height: 100vh;
    display: flex;
    align-items: center;
    justify-content: center;

    @keyframes ldio-lzv6rff8cna {
  0% { opacity: 1 }
  100% { opacity: 0 }
}
.ldio-lzv6rff8cna div {
  left: 94px;
  top: 48px;
  position: absolute;
  animation: ldio-lzv6rff8cna linear 1s infinite;
  background: #ff7a00;
  width: 12px;
  height: 24px;
  border-radius: 6px / 12px;
  transform-origin: 6px 52px;
}.ldio-lzv6rff8cna div:nth-child(1) {
  transform: rotate(0deg);
  animation-delay: -0.9166666666666666s;
  background: #ff7a00;
}.ldio-lzv6rff8cna div:nth-child(2) {
  transform: rotate(30deg);
  animation-delay: -0.8333333333333334s;
  background: #ff7a00;
}.ldio-lzv6rff8cna div:nth-child(3) {
  transform: rotate(60deg);
  animation-delay: -0.75s;
  background: #ff7a00;
}.ldio-lzv6rff8cna div:nth-child(4) {
  transform: rotate(90deg);
  animation-delay: -0.6666666666666666s;
  background: #ff7a00;
}.ldio-lzv6rff8cna div:nth-child(5) {
  transform: rotate(120deg);
  animation-delay: -0.5833333333333334s;
  background: #ff7a00;
}.ldio-lzv6rff8cna div:nth-child(6) {
  transform: rotate(150deg);
  animation-delay: -0.5s;
  background: #ff7a00;
}.ldio-lzv6rff8cna div:nth-child(7) {
  transform: rotate(180deg);
  animation-delay: -0.4166666666666667s;
  background: #ff7a00;
}.ldio-lzv6rff8cna div:nth-child(8) {
  transform: rotate(210deg);
  animation-delay: -0.3333333333333333s;
  background: #ff7a00;
}.ldio-lzv6rff8cna div:nth-child(9) {
  transform: rotate(240deg);
  animation-delay: -0.25s;
  background: #ff7a00;
}.ldio-lzv6rff8cna div:nth-child(10) {
  transform: rotate(270deg);
  animation-delay: -0.16666666666666666s;
  background: #ff7a00;
}.ldio-lzv6rff8cna div:nth-child(11) {
  transform: rotate(300deg);
  animation-delay: -0.08333333333333333s;
  background: #ff7a00;
}.ldio-lzv6rff8cna div:nth-child(12) {
  transform: rotate(330deg);
  animation-delay: 0s;
  background: #ff7a00;
}
.loadingio-spinner-spinner-fc0yl4ooufr {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-lzv6rff8cna {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-lzv6rff8cna div { box-sizing: content-box; }
/* generated by https://loading.io/ */
`

export const Main = styled.main`
    background-color: ivory;
    width: auto;
    height: auto;
    margin-top: 70px;

    @media only screen and (max-width: 400px){
      height: auto;
      width: 100%;
    }
`

export const Content = styled.div`
  width: 100%;
  height: auto;
  margin-top: 50px;
  display: flex;
  justify-content: center;

  @media(min-width: 320px) and (max-width: 890px){
    width: 100%;
  }
`

export const Overlay = styled.div`
  width: 50%;
  height: auto;
  justify-content: center;

  >h1{
    font-family: sans-serif;
    font-size: 2em;
    color: #000000;

    display: flex;
    justify-content: center;
    
    >span{
        color: #FF7A00;
        margin-left: 10px;
    }
  }

  @media(min-width: 320px) and (max-width: 890px){
    width: 100%;
    >h1{
      width: 100%;
      >span{
        margin-left: 0px;
      }
    }
  }
`

export const Introduction = styled.div`
  width: 100%;
  height: auto;
  text-align: center;
  margin-top: 20px;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  
`

export const Abstract = styled.div`
  width: min-content;
  height: auto;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 10px;

  grid-template-columns: 20% 20% 20%;
  grid-template-areas: "esquerda center direita";

  @media(min-width: 320px) and (max-width: 890px){
    display: flex;
    flex-direction: column;
    padding: 0px;
    
  }
`

export const GridLeft = styled.div`
  width: auto;
  height: inherit;
  padding: 20px;
  grid-area: esquerda;

  @media(min-width: 320px) and (max-width: 890px){
    padding: 0;
    margin-top: 20px;
  }
`

export const GridCenter = styled.div`
  width: auto;
  height: inherit;
  padding: 20px;
  grid-area: center;

  @media(min-width: 320px) and (max-width: 890px){
    padding: 0;
    margin-top: 20px;
  }
` 

export const GridRight = styled.div`
  width: 100%;
  height: inherit;
  padding: 20px;
  grid-area: direita;

  @media(min-width: 320px) and (max-width: 890px){
    padding: 0;
    margin-top: 20px;
  }
` 

export const CircleAbstract = styled.div`
  width: 200px;
  height: 200px;
  border-radius: 100%;
  background-color: orange;
  
  margin-left: auto;
  margin-right: auto;
  margin-bottom: 20px;

  display: flex;
  justify-content: center;
  align-items: center;

  @media(min-width: 320px) and (max-width: 890px){
    display: flex;
    flex-direction: column;
    align-items: center;
  }
`

export const ContentServicos = styled.div`
  width: 100%;
  height: auto;
  display: flex;
  justify-content: center;
`

export const OverlayServicos = styled.div`
  width: 15%;
  height: inherit;
  padding: 20px;
  margin-left: 10px;
  display: flex;
  flex-direction: column;
  align-items: center;

  p{
    text-align: center;
    margin-top: 10px;
    
  }

  @media(min-width: 320px) and (max-width: 890px){
    width: 100%;
    display: flex;
    flex-direction: column;
    align-items: center;
    float: none;
    margin-left: 0px;
    p{
      font-size: larger;
    }
  }
`

export const Circle = styled.div`
  width: 100px;
  height: 100px;
  border-radius: 100%;
  display: flex;
  justify-content: center;
  align-items: center;

  img{
    width: 100%;
    height: 100%;
  }

  @media(min-width: 320px) and (max-width: 890px){
    width: 200px;
    height: 200px;
  }
`

export const ContainerButton = styled.div`
  width: 100%;
  height: auto;
  display: flex;
  justify-content: center;
`

export const Button = styled.div`
  width: auto;
  height: auto;
  margin-top: 50px;

  button{
    width: 150px;
    height: 40px;
    background-color: var(--primary);
    border: none;
    color: white;
    font-weight: bold;
    font-family: sans-serif;
    border-radius: 30px;
    cursor: pointer;
  }
`